//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YonetimPaneli.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int BlogId { get; set; }
        public string Baslik { get; set; }
        public string ResimUrl { get; set; }
        public int KategoriId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Icerik { get; set; }
    }
}
