//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YonetimPaneli.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iletisim
    {
        public int IletisimId { get; set; }
        public string Adres { get; set; }
        public string Tel { get; set; }
        public string Facebook { get; set; }
        public string twitter { get; set; }
        public string Instagram { get; set; }
    }
}
